version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  
  celery:
    build: .
    command: bash -c "/wait-for-it.sh rabbitmq:5672 -t 30 && celery -A core worker --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

  

