# Generated by Django 4.1.6 on 2023-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=400)),
                ('loan_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PENDING', 'Under Evaluation')], default='PENDING', max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
